name: Build and Release
on:
- push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - id: s00
        # print repository and ref
        run: |
          echo "Repository: ${{ github.repository }}, Ref: ${{ github.ref }}"